apiVersion: apps/v1
kind: Deployment
metadata:
  name: hihu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hihu
  template:
    metadata:
      labels:
        app: hihu
    spec:
      containers:
      - image: okteto.dev/hihu:latest
        name: hihu
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "c7f77529-93d7-4b66-a619-5aa37386cd14"
        - name: Vless_Path
          value: "/vl5555"
        - name: Vmess_UUID
          value: "c7f77529-93d7-4b66-a619-5aa37386cd14"
        - name: Vmess_Path
          value: "/vm6566"
        - name: Share_Path
          value: "/v2link"
